import pygame


WIDTH = 900
HEIGHT = 600
CELL_SIZE = 30

BLACK = (0,0,0)
WHITE = (255,255,255)

GRIDWITH = WIDTH/CELL_SIZE
GRIDHEIGHT = HEIGHT/CELL_SIZE

DEFAULT_COLOR = "Gray"
FILLED_CELL_COLOR = "Black"
BORDER_COLOR = "White"
HAS_BEEN_SEARCHED_COLOR = "Orange"
IMAGE_SIZE = (CELL_SIZE,CELL_SIZE)
TEXT_COLOR = "WHITE"
FONT = "Arial"
TEXT_SIZE = 25
TEXT_TIME = 180



